export const courses = [
  { value: 'BSIT', label: 'Bachelor of Science in Information Technology' },
  { value: 'BSCS', label: 'Bachelor of Science in Computer Science' },
  { value: 'BST', label: 'Bachelor of Science in Tourism' },
  { value: 'BSHRM', label: 'Bachelor of Science in Hotel and Restaurant Management' },
  { value: 'BSN', label: 'Bachelor of Science in Nursing' },
]

export const students = [
  {
    firstName: 'Maria',
    middleInitial: 'C',
    lastName: 'Santos',
    birthDate: '2002-03-15',
    age: 23,
    streetAddress: '123 Rizal Street',
    barangay: 'Barangay 1',
    city: 'Quezon City',
    province: 'Metro Manila',
    zipCode: '1000',
    course: 'BSIT',
    id: '74d26740-e703-4ca7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Miguel',
    middleInitial: 'A',
    lastName: 'Torres',
    birthDate: '2003-05-30',
    age: 22,
    streetAddress: '987 Aguinaldo Avenue',
    barangay: 'Barangay 2',
    city: 'Paranaque City',
    province: 'Metro Manila',
    zipCode: '1700',
    course: 'BSIT',
    id: '74d26740-e703-4ca7-af36-4faf4b0efcds',
  },
  {
    firstName: 'Valentina',
    middleInitial: 'G',
    lastName: 'Castro',
    birthDate: '2001-10-12',
    age: 23,
    streetAddress: '582 Katipunan Avenue',
    barangay: 'Barangay 3',
    city: 'Quezon City',
    province: 'Metro Manila',
    zipCode: '1108',
    course: 'BSIT',
    id: '74d26740-e703-4ca7-af36-4faf4b0efcda',
  },
  {
    firstName: 'Sebastian',
    middleInitial: 'I',
    lastName: 'Gutierrez',
    birthDate: '2002-08-16',
    age: 22,
    streetAddress: '147 Roxas Boulevard',
    barangay: 'Barangay 4',
    city: 'Manila',
    province: 'Metro Manila',
    zipCode: '1000',
    course: 'BSIT',
    id: '74d26740-e703-4ca7-af36-4faf4b0eecdd',
  },
  {
    firstName: 'Sophia',
    middleInitial: 'L',
    lastName: 'Dela Cruz',
    birthDate: '2003-01-08',
    age: 22,
    streetAddress: '234 Magsaysay Avenue',
    barangay: 'Barangay 5',
    city: 'Quezon City',
    province: 'Metro Manila',
    zipCode: '1100',
    course: 'BSIT',
    id: '74d26740-e703-4da7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Joshua',
    middleInitial: 'R',
    lastName: 'Martinez',
    birthDate: '2001-11-22',
    age: 23,
    streetAddress: '345 Taft Avenue',
    barangay: 'Barangay 6',
    city: 'Manila',
    province: 'Metro Manila',
    zipCode: '1000',
    course: 'BSIT',
    id: '74d26740-e703-4cw7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Angelica',
    middleInitial: 'M',
    lastName: 'Bautista',
    birthDate: '2002-06-14',
    age: 22,
    streetAddress: '456 Orion Street',
    barangay: 'Barangay 7',
    city: 'Makati City',
    province: 'Metro Manila',
    zipCode: '1200',
    course: 'BSIT',
    id: '74d26740-e703-4za7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Rafael',
    middleInitial: 'D',
    lastName: 'Aquino',
    birthDate: '2003-09-03',
    age: 21,
    streetAddress: '567 Marcos Highway',
    barangay: 'Barangay 8',
    city: 'Pasig City',
    province: 'Metro Manila',
    zipCode: '1600',
    course: 'BSIT',
    id: '74d26740-e703-4ea7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Jasmine',
    middleInitial: 'P',
    lastName: 'Lim',
    birthDate: '2002-04-17',
    age: 23,
    streetAddress: '678 Binondo Street',
    barangay: 'Barangay 9',
    city: 'Manila',
    province: 'Metro Manila',
    zipCode: '1006',
    course: 'BSIT',
    id: '74d26740-e703-4fa7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Christopher',
    middleInitial: 'B',
    lastName: 'Navarro',
    birthDate: '2001-12-29',
    age: 23,
    streetAddress: '789 Alabang-Zapote Road',
    barangay: 'Barangay 10',
    city: 'Las Pinas City',
    province: 'Metro Manila',
    zipCode: '1740',
    course: 'BSIT',
    id: '74d26740-e703-4ga7-af36-4faf4b0efcdd',
  },

  // BSCS students (additional 9)
  {
    firstName: 'Juan',
    middleInitial: 'D',
    lastName: 'Cruz',
    birthDate: '2001-07-22',
    age: 24,
    streetAddress: '456 Mabini Avenue',
    barangay: 'Barangay 11',
    city: 'Manila',
    province: 'Metro Manila',
    zipCode: '1000',
    course: 'BSCS',
    id: '74d26740-e703-4ha7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Isabela',
    middleInitial: 'R',
    lastName: 'Reyes',
    birthDate: '2002-02-14',
    age: 23,
    streetAddress: '789 Lopez Jaena St.',
    barangay: 'Barangay 12',
    city: 'Marikina City',
    province: 'Metro Manila',
    zipCode: '1800',
    course: 'BSCS',
    id: '74d26740-e703-4ia7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Marco',
    middleInitial: 'J',
    lastName: 'Villanueva',
    birthDate: '2000-06-11',
    age: 24,
    streetAddress: '102 Kalayaan Ave.',
    barangay: 'Barangay 13',
    city: 'Quezon City',
    province: 'Metro Manila',
    zipCode: '1101',
    course: 'BSCS',
    id: '74d26740-e703-4ja7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Nicole',
    middleInitial: 'F',
    lastName: 'Gonzales',
    birthDate: '2003-12-03',
    age: 21,
    streetAddress: '65 Aurora Blvd.',
    barangay: 'Barangay 14',
    city: 'Quezon City',
    province: 'Metro Manila',
    zipCode: '1100',
    course: 'BSCS',
    id: '74d26740-e703-4ka7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Patrick',
    middleInitial: 'S',
    lastName: 'Lopez',
    birthDate: '2002-05-29',
    age: 22,
    streetAddress: '34 Ortigas Ext.',
    barangay: 'Barangay 15',
    city: 'Pasig City',
    province: 'Metro Manila',
    zipCode: '1600',
    course: 'BSCS',
    id: '74d26740-e703-4la7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Camille',
    middleInitial: 'A',
    lastName: 'Mendoza',
    birthDate: '2001-08-21',
    age: 23,
    streetAddress: '98 Recto Avenue',
    barangay: 'Barangay 16',
    city: 'Manila',
    province: 'Metro Manila',
    zipCode: '1000',
    course: 'BSCS',
    id: '74d26740-e703-4ma7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Ronald',
    middleInitial: 'E',
    lastName: 'Fernandez',
    birthDate: '2000-10-04',
    age: 24,
    streetAddress: '231 West Avenue',
    barangay: 'Barangay 17',
    city: 'Quezon City',
    province: 'Metro Manila',
    zipCode: '1104',
    course: 'BSCS',
    id: '74d26740-e703-4na7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Elaine',
    middleInitial: 'N',
    lastName: 'David',
    birthDate: '2002-09-09',
    age: 22,
    streetAddress: '123 Boni Avenue',
    barangay: 'Barangay 18',
    city: 'Mandaluyong City',
    province: 'Metro Manila',
    zipCode: '1550',
    course: 'BSCS',
    id: '74d26740-e703-4oa7-af36-4faf4b0efcdd',
  },
  {
    firstName: 'Samuel',
    middleInitial: 'H',
    lastName: 'Rosales',
    birthDate: '2003-03-13',
    age: 21,
    streetAddress: '45 Commonwealth Ave.',
    barangay: 'Barangay 19',
    city: 'Quezon City',
    province: 'Metro Manila',
    zipCode: '1121',
    course: 'BSCS',
    id: '74d26740-e703-4pa7-af36-4faf4b0efcdd',
  },

  // BST students
  {
    firstName: 'Clarisse',
    middleInitial: 'T',
    lastName: 'Manalo',
    birthDate: '2002-01-25',
    age: 22,
    streetAddress: '75 España Blvd.',
    barangay: 'Barangay 20',
    city: 'Manila',
    province: 'Metro Manila',
    zipCode: '1000',
    course: 'BST',
    id: '74d26740-e703-4qa7-af36-4faf4b0efcdd',
  },
]
