import type { Product } from '@/types/Product'

export const products: Product[] = [
  {
    id: 1,
    name: 'Wireless Bluetooth Headphones',
    description: 'High-quality over-ear headphones with noise cancellation.',
    price: 5999,
    oldPrice: 6665,
    discount: 10,
    stock: 150,
    image: '/src/assets/products/Wireless Bluetooth Headphones.jpg',
    category: 'Electronics',
    rating: 4.5,
    reviewsCount: 320,
    badge: 'NEW',
    brand: 'SoundMax',
  },
  {
    id: 2,
    name: 'Smartphone 128GB',
    description: 'Latest model with 6.5-inch display and 48MP camera.',
    price: 29999,
    oldPrice: 35293,
    discount: 15,
    stock: 80,
    image: '/src/assets/products/Smartphone 128GB.jpg',
    category: 'Electronics',
    rating: 4.7,
    reviewsCount: 450,
    badge: 'SALE',
    brand: 'TechTrend',
  },
  {
    id: 3,
    name: 'Stainless Steel Water Bottle',
    description: '1L insulated bottle, keeps drinks hot or cold for 24 hours.',
    price: 1499,
    oldPrice: 1578,
    discount: 5,
    stock: 200,
    image: '/src/assets/products/Stainless Steel Water Bottle.jpg',
    category: 'Home & Kitchen',
    rating: 4.3,
    reviewsCount: 180,
    badge: 'NEW',
    brand: 'AquaPure',
  },
  {
    id: 4,
    name: 'Running Shoes Men',
    description: 'Lightweight athletic shoes with breathable mesh.',
    price: 3499,
    oldPrice: 4374,
    discount: 20,
    stock: 120,
    image: '/src/assets/products/Running Shoes Men.jpg',
    category: 'Fashion',
    rating: 4.4,
    reviewsCount: 210,
    badge: 'SALE',
    brand: 'FitStep',
  },
  {
    id: 5,
    name: 'LED Desk Lamp',
    description: 'Adjustable brightness and color temperature.',
    price: 1999,
    oldPrice: 2173,
    discount: 8,
    stock: 90,
    image: '/src/assets/products/LED Desk Lamp.jpg',
    category: 'Home & Kitchen',
    rating: 4.6,
    reviewsCount: 150,
    badge: 'NEW',
    brand: 'BrightHome',
  },
  {
    id: 6,
    name: 'Wireless Mouse',
    description: 'Ergonomic design with 2.4GHz wireless connection.',
    price: 999,
    oldPrice: 1999,
    discount: 0,
    stock: 300,
    image: '/src/assets/products/Wireless Mouse.jpg',
    category: 'Electronics',
    rating: 4.2,
    reviewsCount: 260,
    badge: 'HOT',
    brand: 'TechGear',
  },
  {
    id: 7,
    name: 'Backpack 30L',
    description: 'Water-resistant backpack with laptop compartment.',
    price: 2499,
    oldPrice: 2840,
    discount: 12,
    stock: 110,
    image: '/src/assets/products/Backpack 30L.jpg',
    category: 'Fashion',
    rating: 4.5,
    reviewsCount: 190,
    badge: 'SALE',
    brand: 'TravelPro',
  },
  {
    id: 8,
    name: 'Electric Kettle 1.7L',
    description: 'Fast-boiling kettle with auto shut-off.',
    price: 1799,
    oldPrice: 1999,
    discount: 10,
    stock: 140,
    image: '/src/assets/products/Electric Kettle 1.7L.jpg',
    category: 'Home & Kitchen',
    rating: 4.3,
    reviewsCount: 230,
    badge: 'NEW',
    brand: 'KitchenAid',
  },
  {
    id: 9,
    name: 'Smart Watch',
    description: 'Fitness tracker with heart rate monitor.',
    price: 4999,
    oldPrice: 5881,
    discount: 15,
    stock: 70,
    image: '/src/assets/products/Smart Watch.jpg',
    category: 'Electronics',
    rating: 4.6,
    reviewsCount: 400,
    badge: 'SALE',
    brand: 'FitTech',
  },
  {
    id: 10,
    name: 'Cotton T-Shirt',
    description: 'Comfortable crew neck t-shirt in multiple colors.',
    price: 799,
    oldPrice: 841,
    discount: 5,
    stock: 250,
    image: '/src/assets/products/Cotton T-Shirt.jpg',
    category: 'Fashion',
    rating: 4.1,
    reviewsCount: 300,
    badge: 'HOT',
    brand: 'StyleWear',
  },
  {
    id: 11,
    name: 'Portable Charger 10000mAh',
    description: 'Compact power bank with dual USB ports.',
    price: 1299,
    oldPrice: 1443,
    discount: 10,
    stock: 180,
    image: '/src/assets/products/Portable Charger 10000mAh.jpg',
    category: 'Electronics',
    rating: 4.4,
    reviewsCount: 280,
    badge: 'NEW',
    brand: 'PowerUp',
  },
  {
    id: 12,
    name: 'Non-Stick Frying Pan',
    description: '12-inch pan with durable non-stick coating.',
    price: 1599,
    oldPrice: 1738,
    discount: 8,
    stock: 130,
    image: '/src/assets/products/Non-Stick Frying Pan.jpg',
    category: 'Home & Kitchen',
    rating: 4.5,
    reviewsCount: 200,
    badge: 'SALE',
    brand: 'CookEasy',
  },
  {
    id: 13,
    name: 'Gaming Keyboard',
    description: 'Mechanical keyboard with RGB backlighting.',
    price: 3999,
    oldPrice: 4544,
    discount: 12,
    stock: 100,
    image: '/src/assets/products/Gaming Keyboard.jpg',
    category: 'Electronics',
    rating: 4.7,
    reviewsCount: 350,
    badge: 'HOT',
    brand: 'GamePro',
  },
  {
    id: 14,
    name: 'Yoga Mat',
    description: 'Non-slip 6mm thick mat for yoga and fitness.',
    price: 999,
    oldPrice: 1052,
    discount: 5,
    stock: 200,
    image: '/src/assets/products/Yoga Mat.jpg',
    category: 'Sports & Outdoors',
    rating: 4.3,
    reviewsCount: 170,
    badge: 'NEW',
    brand: 'FitLife',
  },
  {
    id: 15,
    name: 'Wireless Earbuds',
    description: 'True wireless earbuds with 15-hour playtime.',
    price: 2499,
    oldPrice: 2777,
    discount: 10,
    stock: 160,
    image: '/src/assets/products/Wireless Earbuds.jpg',
    category: 'Electronics',
    rating: 4.5,
    reviewsCount: 310,
    badge: 'SALE',
    brand: 'SoundWave',
  },
  {
    id: 16,
    name: 'Sunglasses',
    description: 'Polarized UV protection sunglasses.',
    price: 1499,
    oldPrice: 1764,
    discount: 15,
    stock: 140,
    image: '/src/assets/products/Sunglasses.jpg',
    category: 'Fashion',
    rating: 4.2,
    reviewsCount: 220,
    badge: 'HOT',
    brand: 'SunStyle',
  },
  {
    id: 17,
    name: 'Air Fryer 5L',
    description: 'Healthy cooking with rapid air technology.',
    price: 4999,
    oldPrice: 6249,
    discount: 20,
    stock: 90,
    image: '/src/assets/products/Air Fryer 5L.png',
    category: 'Home & Kitchen',
    rating: 4.6,
    reviewsCount: 270,
    badge: 'SALE',
    brand: 'HealthyCook',
  },
  {
    id: 18,
    name: 'Fitness Tracker',
    description: 'Tracks steps, calories, and sleep.',
    price: 1999,
    oldPrice: 2221,
    discount: 10,
    stock: 110,
    image: '/src/assets/products/Fitness Tracker.jpg',
    category: 'Electronics',
    rating: 4.4,
    reviewsCount: 240,
    badge: 'NEW',
    brand: 'FitTech',
  },
  {
    id: 19,
    name: 'Ceramic Mug Set',
    description: 'Set of 4 colorful ceramic mugs, 350ml.',
    price: 1199,
    oldPrice: 1263,
    discount: 5,
    stock: 180,
    image: '/src/assets/products/Ceramic Mug Set.jpg',
    category: 'Home & Kitchen',
    rating: 4.3,
    reviewsCount: 160,
    badge: 'HOT',
    brand: 'HomeVibe',
  },
  {
    id: 20,
    name: 'Laptop Stand',
    description: 'Adjustable aluminum stand for laptops.',
    price: 1699,
    oldPrice: 1847,
    discount: 8,
    stock: 130,
    image: '/src/assets/products/Laptop Stand.jpg',
    category: 'Electronics',
    rating: 4.5,
    reviewsCount: 200,
    badge: 'NEW',
    brand: 'TechSupport',
  },
  {
    id: 21,
    name: 'Denim Jeans',
    description: 'Slim-fit jeans with stretch fabric.',
    price: 1999,
    oldPrice: 2352,
    discount: 15,
    stock: 150,
    image: '/src/assets/products/Denim Jeans.jpg',
    category: 'Fashion',
    rating: 4.4,
    reviewsCount: 230,
    badge: 'SALE',
    brand: 'StyleWear',
  },
  {
    id: 22,
    name: 'Blender 1.5L',
    description: 'Powerful blender with multiple speeds.',
    price: 2999,
    oldPrice: 3332,
    discount: 10,
    stock: 100,
    image: '/src/assets/products/Blender 1.5L.jpg',
    category: 'Home & Kitchen',
    rating: 4.6,
    reviewsCount: 190,
    badge: 'NEW',
    brand: 'KitchenPro',
  },
  {
    id: 23,
    name: 'Portable Speaker',
    description: 'Bluetooth speaker with 10-hour battery.',
    price: 2499,
    oldPrice: 2840,
    discount: 12,
    stock: 120,
    image: '/src/assets/products/Portable Speaker.jpg',
    category: 'Electronics',
    rating: 4.5,
    reviewsCount: 260,
    badge: 'SALE',
    brand: 'SoundMax',
  },
  {
    id: 24,
    name: 'Camping Tent 4-Person',
    description: 'Waterproof tent with easy setup.',
    price: 4999,
    oldPrice: 6249,
    discount: 20,
    stock: 80,
    image: '/src/assets/products/Camping Tent 4-Person.jpg',
    category: 'Sports & Outdoors',
    rating: 4.7,
    reviewsCount: 150,
    badge: 'HOT',
    brand: 'OutdoorLife',
  },
  {
    id: 25,
    name: 'Electric Toothbrush',
    description: 'Rechargeable toothbrush with multiple modes.',
    price: 1999,
    oldPrice: 2221,
    discount: 10,
    stock: 140,
    image: '/src/assets/products/Electric Toothbrush.jpg',
    category: 'Health & Personal Care',
    rating: 4.4,
    reviewsCount: 200,
    badge: 'NEW',
    brand: 'SmileCare',
  },
  {
    id: 26,
    name: 'Winter Jacket',
    description: 'Insulated jacket with waterproof layer.',
    price: 3999,
    oldPrice: 4705,
    discount: 15,
    stock: 90,
    image: '/src/assets/products/Winter Jacket.jpg',
    category: 'Fashion',
    rating: 4.6,
    reviewsCount: 220,
    badge: 'SALE',
    brand: 'WarmWear',
  },
  {
    id: 27,
    name: 'Coffee Maker',
    description: '12-cup drip coffee maker with timer.',
    price: 2499,
    oldPrice: 2716,
    discount: 8,
    stock: 110,
    image: '/src/assets/products/Coffee Maker.jpg',
    category: 'Home & Kitchen',
    rating: 4.3,
    reviewsCount: 180,
    badge: 'NEW',
    brand: 'BrewMaster',
  },
  {
    id: 28,
    name: 'Gaming Mouse',
    description: 'High-precision mouse with RGB lighting.',
    price: 1999,
    oldPrice: 2221,
    discount: 10,
    stock: 130,
    image: '/src/assets/products/Gaming Mouse.jpg',
    category: 'Electronics',
    rating: 4.5,
    reviewsCount: 270,
    badge: 'HOT',
    brand: 'GamePro',
  },
  {
    id: 29,
    name: 'Dumbbell Set 20kg',
    description: 'Adjustable宝',
    price: 3499,
    oldPrice: 3976,
    discount: 12,
    stock: 100,
    image: '/src/assets/products/Dumbbell Set 20kg.jpg',
    category: 'Sports & Outdoors',
    rating: 4.6,
    reviewsCount: 190,
    badge: 'SALE',
    brand: 'FitLife',
  },
  {
    id: 30,
    name: 'Microwave Oven 20L',
    description: 'Compact microwave with defrost function.',
    price: 3999,
    oldPrice: 4443,
    discount: 10,
    stock: 80,
    image: '/src/assets/products/Microwave Oven 20L.jpg',
    category: 'Home & Kitchen',
    rating: 4.4,
    reviewsCount: 210,
    badge: 'NEW',
    brand: 'KitchenAid',
  },
]
